php-apache:
  build: .
  ports:
    - 8000:80
  links:
    - mysql
  volumes:
    - ./www:/var/www/html
    - ./apache2.conf:/etc/apache2/apache2.conf

mysql:
  image: mysql:latest
  command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
  volumes_from:
    - data
  environment:
    - MYSQL_ROOT_PASSWORD=hidden
    - MYSQL_USER=shopuser
    - MYSQL_PASSWORD=secret
    - MYSQL_DATABASE=shopware

data:
  image: mysql:latest
  volumes:
    - /var/lib/mysql
  command: "true"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 8080:80
  links:
    - mysql
  environment:
    PMA_HOST: mysql
